export const ProductTypes={
    All_Products:"All_Products",
    CART_PRODUCT:"CART_PRODUCT",
    REMOVE_CART:"REMOVE_CART",
    WOMEN_PRODUCTS:"WOMEN_PRODUCTS",
    MEN_WATCHES:"MEN_WATCHES",
    JEWELLERY:"JEWELLERY",
    BEAUTY:'BEAUTY',
    BAGS:'BAGS',
    FRAGRANCES:'FRAGRANCES',
    TOPS:'TOPS',
    SHOES:'SHOES',
}